name: al_ma
description: A flutter project to buy, rate and review mobile products for a client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  auto_route: ^0.6.7
  stacked: ^1.7.6
  stacked_services: ^0.5.4+3
  stacked_hooks: ^0.1.3
  path_provider: ^1.6.18
  get_it: '<=4.0.4'
  injectable: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: 
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Sans_Bold
      fonts:
        - asset: fonts/BalooTammudu2-Bold.ttf
          weight: 700
    - family: Sans_ExtraBold
      fonts:
        - asset: fonts/BalooTammudu2-ExtraBold.ttf
          weight: 800
    - family: Sans_Medium
      fonts:
        - asset: fonts/BalooTammudu2-Medium.ttf
          weight: 500
    - family: Sans_Regular
      fonts:
        - asset: fonts/BalooTammudu2-Regular.ttf
          weight: 400
    - family: Sans_SemiBold
      fonts:
        - asset: fonts/BalooTammudu2-SemiBold.ttf
          weight: 600




    - family: Serif-sans_SemiBoldItalic
      fonts:
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Serif-sans_LightItalic
      fonts:
        - asset: fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
    - family: Serif-sans_ExtraBold
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Serif-sans_ExtraBoldItalic
      fonts:
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Serif-sans_Italic
      fonts:
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
    - family: Serif-sans_Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
    - family: Serif-sans_Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Serif-sans_SemiBold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Serif-sans_Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Serif-sans_BoldItalic
      fonts:
        - asset: fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

